# Generated by Django 3.1.1 on 2020-09-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_or_Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Movie Title')),
                ('length', models.CharField(max_length=40, verbose_name='Movie Length')),
                ('stars', models.TextField(verbose_name='Stars')),
                ('director', models.CharField(max_length=80, verbose_name='Director')),
                ('total_season', models.IntegerField(blank=True, null=True, verbose_name='Total Season')),
                ('review_img', models.TextField(verbose_name='Review Image')),
                ('category', models.ManyToManyField(to='Movie_Serie.Category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_Serie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True, verbose_name='Season')),
                ('episode_number', models.IntegerField(blank=True, null=True, verbose_name='Episode')),
                ('link', models.TextField(unique=True, verbose_name='Link')),
                ('movie_or_serie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_Serie.movie_or_serie')),
            ],
        ),
    ]
