# Generated by Django 3.1.1 on 2020-09-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0005_auto_20200922_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='available_fhd',
            field=models.BooleanField(default=False, verbose_name='FHD Available'),
        ),
        migrations.AlterField(
            model_name='url',
            name='available_hd',
            field=models.BooleanField(default=False, verbose_name='HD Available'),
        ),
    ]
