# Generated by Django 3.1.1 on 2020-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0008_movie_or_serie_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='available_4k',
        ),
        migrations.RemoveField(
            model_name='url',
            name='available_fhd',
        ),
        migrations.RemoveField(
            model_name='url',
            name='available_hd',
        ),
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_4k',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='4K Available'),
        ),
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_fhd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='FHD Available'),
        ),
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_hd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HD Available'),
        ),
    ]
