# Generated by Django 3.1.1 on 2020-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0011_auto_20200923_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_or_serie',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
