# Generated by Django 3.1.1 on 2020-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0012_movie_or_serie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_or_serie',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
