# Generated by Django 3.1.1 on 2020-09-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0013_auto_20200923_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_or_serie',
            name='available_4k',
        ),
        migrations.RemoveField(
            model_name='movie_or_serie',
            name='available_fhd',
        ),
        migrations.RemoveField(
            model_name='movie_or_serie',
            name='available_hd',
        ),
    ]
