# Generated by Django 3.1.1 on 2020-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0014_auto_20200927_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_4k',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='4K Available'),
        ),
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_fhd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='FHD Available'),
        ),
        migrations.AddField(
            model_name='movie_or_serie',
            name='available_hd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HD Available'),
        ),
    ]
