# Generated by Django 3.1.1 on 2020-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0015_auto_20200927_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_or_serie',
            name='imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='IMDb'),
        ),
    ]
