# Generated by Django 3.1.1 on 2020-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0016_movie_or_serie_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_or_serie',
            name='imdb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='IMDb'),
        ),
    ]
