# Generated by Django 3.1.1 on 2020-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Serie', '0017_auto_20200927_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_or_serie',
            name='imdb',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='IMDb'),
        ),
    ]
